# GoReleaser 配置文件
# 用于自动化构建和发布多个平台版本

version: 2

# 项目名称
project_name: gocalc

# 发布配置
release:
  # GitHub发布配置
  github:
    owner: panyingyun  # 修改为你的GitHub用户名
    name: gocalc     # 修改为你的仓库名
  
  # 发布模式：替换或跳过已存在的发布
  mode: replace
  
  # 发布前执行的命令（可选）
  # prerelease: auto  # 自动检测是否为预发布版本
  
  # 发布说明模板
  header: |
    ## {{ .ProjectName }} {{ .Tag }}
    
    发布版本 {{ .Tag }}
    
  footer: |
    ---
    
    由 [GoReleaser](https://github.com/goreleaser/goreleaser) 自动生成

# 构建配置 - 支持多个平台和架构
builds:
  # Linux 构建配置
  - id: linux
    # 主程序入口
    main: .
    
    # 二进制文件名称
    binary: gocalc
    
    # 构建命令
    goos:
      - linux
    
    # 架构
    goarch:
      - amd64
    
    # 构建标志
    flags:
      - -trimpath
    
    # LDFlags
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
  
  # Windows 构建配置（使用 windowsgui 标志隐藏控制台）
  - id: windows
    # 主程序入口
    main: .
    
    # 二进制文件名称
    binary: gocalc
    
    # 构建命令
    goos:
      - windows
    
    # 架构
    goarch:
      - amd64
    
    # 构建标志
    flags:
      - -trimpath
    
    # LDFlags - Windows 特殊处理：使用 -H windowsgui 隐藏控制台窗口
    ldflags:
      - -s -w
      - -H windowsgui
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
    
    # 忽略错误
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

# 归档配置
archives:
  - id: default
    # 文件名模板
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    
    # 包含的文件
    files:
      - LICENSE
      - README.md

# 校验和配置
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# 快照配置（用于测试）
snapshot: {}

# Changelog配置
changelog:
  # 使用git日志生成changelog
  use: git
  # 过滤提交信息
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^update:"
